title: Suneel Korada
logo: "/profile.png?raw=true"
description: >
 <br />
 Architect / Principle Engineer
 <br />
 <a href="mailto:suneel68@gmail.com">suneel68@gmail.com</a>
 <br />
 <a href="https://www.linkedin.com/in/sk68/">LinkedIn Profile</a>
 <br/>
theme: jekyll-theme-minimal
